on:
  push:
    branches: 
      - master
name: Master Build/Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v2.4.0
      with:
        java-version: '11'
    - name: Update permissions on mvnw
      run: chmod 700 mvnw
    - name: Build, Test
      run: ./mvnw clean verify --no-transfer-progress
